name: Python Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '19 12 * * 5'
      
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.14.1
        continue-on-error: false
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
